spring:
  application:
    name: eureka_server

server:
  port: 8002

eureka:
  instance:
    hostname: point2

  client:
    serviceUrl:
      defaultZone: http://point1:8001/eureka/
    register-with-eureka: true
    fetch-registry: true