spring:
  application:
    name: eureka_server

server:
  port: 8001

eureka:
  instance:
    hostname: point1

  client:
    serviceUrl:
      defaultZone: http://point2:8002/eureka/
    register-with-eureka: true
    fetch-registry: true