spring:
  application:
    name: eureka_server

server:
  port: 8001

eureka:
  instance:
    hostname: point1

  client:
    serviceUrl:
      #defaultZone: http://point2:8002/eureka/
      defaultZone: http://point1:8001/eureka/
    register-with-eureka: false
    fetch-registry: false
